from_latest_tag = true
ignore_merge_commits = true
ignore_fixup_commits = true
disable_changelog = false
disable_bump_commit = false
generate_mono_repository_global_tag = false
generate_mono_repository_package_tags = false
branch_whitelist = ["main", "release/**"]
skip_ci = "[skip ci]"
skip_untracked = false

pre_bump_hooks = [
    "echo -n '{{version}}' > VERSION",
]
post_bump_hooks = []
pre_package_bump_hooks = []
post_package_bump_hooks = []

[git_hooks]

[commit_types]

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
owner = "sibeov"
repository = "nix-shell-templates"
authors = [
    { signature = "sibeov", username = "sibeov" },
]

[bump_profiles]

[packages]
